sudo: false
language: python

python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"

install:
  - pip install pytest-cov
  - pip install -e .

script:
  - py.test --cov=flask_zodb tests.py

after_success:
  - pip install coveralls
  - coveralls
